/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import java.awt.Color;
import javax.swing.JTabbedPane;
import java.awt.Font;
import javax.swing.SwingConstants;

/**
 *
 * @author NavyaSai
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    String card_no, ssn, address,fname,lname,name, state,city, email,phone;
    String isbn,branch_id,loan_id,title,author,search;
    String message;
    Double fine_amt,pay;
    String paid,book_returned;
    int flag=0;
    static DefaultTableModel model1 = new DefaultTableModel();
    static DefaultTableModel model2 = new DefaultTableModel();
    static DefaultTableModel model3 = new DefaultTableModel();
    
    public NewJFrame() {
        initComponents();
     /* Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
      setBounds(0,0,screenSize.width, screenSize.height); */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel26 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane1.setTabPlacement(JTabbedPane.BOTTOM);
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane2.setTabPlacement(JTabbedPane.LEFT);
        jTabbedPane2.setBounds(10, 62, 967, 375);
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setBounds(333, 56, 56, 26);
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setBounds(437, 55, 186, 28);
        jTextField3 = new javax.swing.JTextField();
        jTextField3.setBounds(634, 94, 186, 28);
        jTextField3.setVisible(false);
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setBounds(316, 97, 85, 22);
        jTextField4 = new javax.swing.JTextField();
        jTextField4.setBounds(437, 94, 186, 28);
        jLabel13 = new javax.swing.JLabel();
        jLabel13.setBounds(574, 133, 85, 22);
        jButton6 = new javax.swing.JButton();
        jButton6.setBounds(462, 166, 115, 31);
        jLabel23 = new javax.swing.JLabel();
        jLabel23.setBounds(10, 258, 854, 42);
        jLabel28 = new javax.swing.JLabel();
        jLabel28.setBounds(408, 97, 19, 22);
        jPanel7 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton5.setBounds(362, 210, 135, 31);
        jLabel15 = new javax.swing.JLabel();
        jLabel15.setBounds(104, 30, 78, 22);
        jTextField14 = new javax.swing.JTextField();
        jTextField14.setBounds(256, 27, 148, 28);
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox4.setBounds(533, 26, 281, 31);
        jButton9 = new javax.swing.JButton();
        jButton9.setBounds(410, 26, 117, 31);
        jLabel30 = new javax.swing.JLabel();
        jLabel30.setBounds(219, 30, 19, 22);
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane2.setBounds(29, 77, 835, 123);
        jTable2 = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        jButton12.setBounds(362, 273, 135, 31);
        jLabel31 = new javax.swing.JLabel();
        jLabel31.setBounds(137, 308, 833, 51);
        jButton13 = new javax.swing.JButton();
        jButton13.setBounds(362, 241, 135, 31);

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog1.setBounds(new java.awt.Rectangle(50, 50, 600, 500));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Do You Want to Pay Fine ?");

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("YES");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("NO");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jDialog1Layout.createSequentialGroup()
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(95, 95, 95)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(112, 112, 112))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 204, 204));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        model2.addColumn("ISBN");
        model2.addColumn("Book Title");
        model2.addColumn("Author");
        model2.addColumn("Branch ID");
        model2.addColumn("Branch Name");
        model2.addColumn("No. of Copies");
        model2.addColumn("Available Copies");
        
        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ISBN *");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Card No. *");

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new Font("Comic Sans MS", Font.PLAIN, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("* required");

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("Check Out");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel11.setHorizontalAlignment(SwingConstants.CENTER);
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        
                jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jLabel8.setText("First Name *");
                
                        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                        jTextField8.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField8ActionPerformed(evt);
                            }
                        });
                        
                                jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                                jLabel9.setText("SSN * (xxx-xx-xxxx)");
                                
                                        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                                        jTextField9.setToolTipText("In XXX-XX-XXXX format");
                                        jTextField9.addActionListener(new java.awt.event.ActionListener() {
                                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                jTextField9ActionPerformed(evt);
                                            }
                                        });
                                        
                                                jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                                                jLabel10.setText("Address *");
                                                
                                                        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                                                        jTextField10.addActionListener(new java.awt.event.ActionListener() {
                                                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                                jTextField10ActionPerformed(evt);
                                                            }
                                                        });
                                                        
                                                                jLabel11.setFont(new Font("Comic Sans MS", Font.PLAIN, 10)); // NOI18N
                                                                jLabel11.setForeground(Color.RED);
                                                                jLabel11.setText("* required");
                                                                
                                                                        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                                                                        jButton3.setText("Add");
                                                                        jButton3.addActionListener(new java.awt.event.ActionListener() {
                                                                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                                                jButton3ActionPerformed(evt);
                                                                            }
                                                                        });
                                                                        
                                                                                jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                                                                                jLabel17.setText("Last Name *");
                                                                                
                                                                                        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                                                                                        jTextField11.addActionListener(new java.awt.event.ActionListener() {
                                                                                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                                                                jTextField11ActionPerformed(evt);
                                                                                            }
                                                                                        });
                                                                                        
                                                                                                jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                                                                                                jLabel18.setText("Email");
                                                                                                
                                                                                                        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                                                                                                        jLabel19.setText("City *");
                                                                                                        
                                                                                                                jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                                                                                                                jLabel20.setText("State *");
                                                                                                                
                                                                                                                        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                                                                                                                        jLabel21.setText("Phone");
                                                                                                                        
                                                                                                                                jTextField15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                                                                                                                                jTextField15.addActionListener(new java.awt.event.ActionListener() {
                                                                                                                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                                                                                                        jTextField15ActionPerformed(evt);
                                                                                                                                    }
                                                                                                                                });
                                                                                                                                
                                                                                                                                        jTextField16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                                                                                                                                        jTextField16.addActionListener(new java.awt.event.ActionListener() {
                                                                                                                                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                                                                                                                jTextField16ActionPerformed(evt);
                                                                                                                                            }
                                                                                                                                        });
                                                                                                                                        
                                                                                                                                                jTextField17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                                                                                                                                                jTextField17.addActionListener(new java.awt.event.ActionListener() {
                                                                                                                                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                                                                                                                        jTextField17ActionPerformed(evt);
                                                                                                                                                    }
                                                                                                                                                });
                                                                                                                                                
                                                                                                                                                        jTextField18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                                                                                                                                                        jTextField18.addActionListener(new java.awt.event.ActionListener() {
                                                                                                                                                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                                                                                                                                jTextField18ActionPerformed(evt);
                                                                                                                                                            }
                                                                                                                                                        });
                                                                                                                                                        
                                                                                                                                                                javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
                                                                                                                                                                jPanel10Layout.setHorizontalGroup(
                                                                                                                                                                	jPanel10Layout.createParallelGroup(Alignment.TRAILING)
                                                                                                                                                                		.addGroup(jPanel10Layout.createSequentialGroup()
                                                                                                                                                                			.addGroup(jPanel10Layout.createParallelGroup(Alignment.TRAILING)
                                                                                                                                                                				.addGroup(jPanel10Layout.createSequentialGroup()
                                                                                                                                                                					.addContainerGap()
                                                                                                                                                                					.addComponent(jLabel11))
                                                                                                                                                                				.addGroup(jPanel10Layout.createSequentialGroup()
                                                                                                                                                                					.addContainerGap()
                                                                                                                                                                					.addGroup(jPanel10Layout.createParallelGroup(Alignment.TRAILING)
                                                                                                                                                                						.addComponent(jLabel8)
                                                                                                                                                                						.addComponent(jLabel9)
                                                                                                                                                                						.addComponent(jLabel19)
                                                                                                                                                                						.addComponent(jLabel18))
                                                                                                                                                                					.addGap(18)
                                                                                                                                                                					.addGroup(jPanel10Layout.createParallelGroup(Alignment.LEADING, false)
                                                                                                                                                                						.addComponent(jTextField8)
                                                                                                                                                                						.addComponent(jTextField9, GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                                                                                                                                                						.addComponent(jTextField10)
                                                                                                                                                                						.addComponent(jTextField11))
                                                                                                                                                                					.addPreferredGap(ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                                                                                                                                                					.addGroup(jPanel10Layout.createParallelGroup(Alignment.TRAILING, false)
                                                                                                                                                                						.addGroup(jPanel10Layout.createSequentialGroup()
                                                                                                                                                                							.addGroup(jPanel10Layout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                								.addComponent(jLabel20)
                                                                                                                                                                								.addComponent(jLabel21))
                                                                                                                                                                							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                                                                                							.addGroup(jPanel10Layout.createParallelGroup(Alignment.TRAILING)
                                                                                                                                                                								.addComponent(jTextField17, GroupLayout.PREFERRED_SIZE, 228, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                								.addComponent(jTextField18, GroupLayout.PREFERRED_SIZE, 228, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                								.addComponent(jButton3, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)))
                                                                                                                                                                						.addGroup(jPanel10Layout.createSequentialGroup()
                                                                                                                                                                							.addGroup(jPanel10Layout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                								.addComponent(jLabel17, GroupLayout.PREFERRED_SIZE, 99, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                								.addComponent(jLabel10))
                                                                                                                                                                							.addGap(26)
                                                                                                                                                                							.addGroup(jPanel10Layout.createParallelGroup(Alignment.TRAILING)
                                                                                                                                                                								.addComponent(jTextField15, GroupLayout.PREFERRED_SIZE, 228, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                								.addComponent(jTextField16, GroupLayout.PREFERRED_SIZE, 228, GroupLayout.PREFERRED_SIZE))))))
                                                                                                                                                                			.addGap(70))
                                                                                                                                                                );
                                                                                                                                                                jPanel10Layout.setVerticalGroup(
                                                                                                                                                                	jPanel10Layout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                		.addGroup(jPanel10Layout.createSequentialGroup()
                                                                                                                                                                			.addGap(48)
                                                                                                                                                                			.addGroup(jPanel10Layout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                				.addComponent(jTextField15, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                				.addGroup(jPanel10Layout.createParallelGroup(Alignment.BASELINE)
                                                                                                                                                                					.addComponent(jTextField8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                					.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                					.addComponent(jLabel17, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)))
                                                                                                                                                                			.addGap(18)
                                                                                                                                                                			.addGroup(jPanel10Layout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                				.addGroup(jPanel10Layout.createSequentialGroup()
                                                                                                                                                                					.addGroup(jPanel10Layout.createParallelGroup(Alignment.BASELINE)
                                                                                                                                                                						.addComponent(jTextField16, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                						.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                					.addGap(18)
                                                                                                                                                                					.addGroup(jPanel10Layout.createParallelGroup(Alignment.BASELINE)
                                                                                                                                                                						.addComponent(jTextField17, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                						.addComponent(jLabel20))
                                                                                                                                                                					.addGap(18)
                                                                                                                                                                					.addGroup(jPanel10Layout.createParallelGroup(Alignment.BASELINE)
                                                                                                                                                                						.addComponent(jTextField18, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                						.addComponent(jLabel21)))
                                                                                                                                                                				.addGroup(jPanel10Layout.createSequentialGroup()
                                                                                                                                                                					.addGroup(jPanel10Layout.createParallelGroup(Alignment.BASELINE)
                                                                                                                                                                						.addComponent(jTextField11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                						.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                					.addGap(18)
                                                                                                                                                                					.addGroup(jPanel10Layout.createParallelGroup(Alignment.TRAILING)
                                                                                                                                                                						.addComponent(jTextField9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                						.addComponent(jLabel19))
                                                                                                                                                                					.addGap(18)
                                                                                                                                                                					.addGroup(jPanel10Layout.createParallelGroup(Alignment.BASELINE)
                                                                                                                                                                						.addComponent(jTextField10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                						.addComponent(jLabel18))))
                                                                                                                                                                			.addGap(18)
                                                                                                                                                                			.addComponent(jLabel11)
                                                                                                                                                                			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                                                                                                			.addComponent(jButton3)
                                                                                                                                                                			.addContainerGap(26, Short.MAX_VALUE))
                                                                                                                                                                );
                                                                                                                                                                jPanel10.setLayout(jPanel10Layout);
                                                                                                                                                                
                                                                                                                                                                        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                                                                                                                                                                        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                                                                                                                                                                        
                                                                                                                                                                                javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
                                                                                                                                                                                jPanel8.setLayout(jPanel8Layout);
                                                                                                                                                                                jPanel8Layout.setHorizontalGroup(
                                                                                                                                                                                    jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                                                                                                                                                                        .addGap(0, 82, Short.MAX_VALUE)
                                                                                                                                                                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                                                                                                                                                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                .addGap(203, 203, 203))
                                                                                                                                                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                                                                                                                                                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                .addGap(29, 29, 29))))
                                                                                                                                                                                );
                                                                                                                                                                                jPanel8Layout.setVerticalGroup(
                                                                                                                                                                                    jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                                                                                                                                                        .addContainerGap()
                                                                                                                                                                                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                        .addGap(11, 11, 11))
                                                                                                                                                                                );
                                                                                                                                                                                
                                                                                                                                                                                        jTabbedPane2.addTab("New User", jPanel8);

        jLabel23.setFont(new Font("Comic Sans MS", Font.PLAIN, 13)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("ID");

        jTabbedPane2.addTab("Check Out", jPanel6);
        jPanel6.setLayout(null);
        jPanel6.add(jLabel2);
        jPanel6.add(jLabel4);
        jPanel6.add(jTextField1);
        jPanel6.add(jButton6);
        jPanel6.add(jLabel28);
        jPanel6.add(jTextField4);
        jPanel6.add(jTextField3);
        jPanel6.add(jLabel13);
        jPanel6.add(jLabel23);

        jPanel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Show ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("ISBN");

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("First Name");

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Card No.");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane1.setHorizontalScrollBar(null);

        jTable3.setBackground(new java.awt.Color(204, 204, 255));
        jTable3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Card Number", "Borrower Name", "Loan Id", "Branch Id", "Fines"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setShowHorizontalLines(false);
        jTable3.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTable3);
        
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setIconTextGap(7);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Last Name");

        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("Check In");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setText("ID");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7Layout.setHorizontalGroup(
        	jPanel7Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel7Layout.createSequentialGroup()
        			.addContainerGap(36, Short.MAX_VALUE)
        			.addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, 788, GroupLayout.PREFERRED_SIZE)
        			.addGap(63))
        		.addGroup(Alignment.LEADING, jPanel7Layout.createSequentialGroup()
        			.addGap(20)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 857, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        		.addGroup(Alignment.LEADING, jPanel7Layout.createSequentialGroup()
        			.addGap(78)
        			.addGroup(jPanel7Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel7)
        				.addComponent(jLabel5))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel29)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel7Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel7Layout.createSequentialGroup()
        					.addGroup(jPanel7Layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(jTextField7)
        						.addComponent(jTextField5, GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
        					.addGap(128)
        					.addGroup(jPanel7Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel6)
        						.addComponent(jLabel25)))
        				.addGroup(jPanel7Layout.createSequentialGroup()
        					.addGap(9)
        					.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 154, GroupLayout.PREFERRED_SIZE)))
        			.addGap(18)
        			.addGroup(jPanel7Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jButton7)
        				.addGroup(jPanel7Layout.createParallelGroup(Alignment.LEADING, false)
        					.addComponent(jTextField6)
        					.addComponent(jTextField12, GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
        			.addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
        	jPanel7Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel7Layout.createSequentialGroup()
        			.addContainerGap(50, Short.MAX_VALUE)
        			.addGroup(jPanel7Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel7Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel7Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jTextField6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(18)
        			.addGroup(jPanel7Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel7)
        				.addComponent(jLabel25)
        				.addComponent(jTextField12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel29)
        				.addComponent(jTextField7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel7Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton2)
        				.addComponent(jButton7))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE)
        			.addGap(43)
        			.addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        jPanel7.setLayout(jPanel7Layout);

        jTable3.setModel(model1);
        model1.addColumn("ISBN");
        model1.addColumn("Card No");
        model1.addColumn("Borrower Name");
        model1.addColumn("Loan Id");
        model1.addColumn("Branch Id");
        model1.addColumn("Fine Amt");
        jTable3.getColumnModel().getColumn(4).setMinWidth(0);
        jTable3.getColumnModel().getColumn(4).setMaxWidth(0);

        jTabbedPane2.addTab("Check In", jPanel7);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Pay Fine");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Card No.");

        jTextField14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox4.setText("Show Previously Paid Fines");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9.setText("Get Details");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setText("ID");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton12.setText("Update ");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton13.setText("Total Fine");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jTable2.setModel(model3);
        model3.addColumn("Loan Id");
        model3.addColumn("ISBN");
        model3.addColumn("Fine Amt");
        model3.addColumn("Paid");
        model3.addColumn("Book Returned");
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton1.setBounds(467, 229, 126, 32);
        jScrollPane6 = new javax.swing.JScrollPane();
        jScrollPane6.setBounds(20, 70, 901, 150);
        jTable1 = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jLabel24.setBounds(-19, 35, 1081, 34);
        jButton10 = new javax.swing.JButton();
        jButton10.setBounds(467, 267, 126, 31);
        jButton11 = new javax.swing.JButton();
        jButton11.setBounds(467, 305, 126, 31);
        jTextField13 = new javax.swing.JTextField();
        jTextField13.setBounds(253, 231, 185, 28);
        jLabel14 = new javax.swing.JLabel();
        jLabel14.setForeground(Color.BLACK);
        jLabel14.setBounds(20, 234, 223, 22);
        
                jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jButton1.setText("Search");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                    }
                });
                        
                                jScrollPane6.setBorder(null);
                                jScrollPane6.setForeground(java.awt.Color.lightGray);
                                jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
                                
                                        jTable1.setBackground(new java.awt.Color(204, 204, 204));
                                        jTable1.setForeground(getBackground());
                                        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                            new Object [][] {

                                            },
                                            new String [] {
                                                "ISBN", "BOOK TITLE", "AUTHOR", "BRANCH ID", "No of Copies", "Available Copies"
                                            }
                                        ) {
                                            boolean[] canEdit = new boolean [] {
                                                false, false, false, false, false, false
                                            };

                                            public boolean isCellEditable(int rowIndex, int columnIndex) {
                                                return canEdit [columnIndex];
                                            }
                                        });
                                        jTable1.setShowHorizontalLines(false);
                                       
                                        jScrollPane6.setViewportView(jTable1);
                                        
                                                jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                                                jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                                                
                                                        jButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                                                        jButton10.setText("Check In");
                                                        jButton10.addActionListener(new java.awt.event.ActionListener() {
                                                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                                jButton10ActionPerformed(evt);
                                                            }
                                                        });
                                                        
                                                                jButton11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                                                                jButton11.setText("Check Out");
                                                                jButton11.addActionListener(new java.awt.event.ActionListener() {
                                                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                                        jButton11ActionPerformed(evt);
                                                                    }
                                                                });
                                                                
                                                                        jTextField13.setFont(new java.awt.Font("Tahoma", 0, 18));
                                                                        
                                                                                jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                                                                                jLabel14.setText("Enter ISBN/ Title/ Author");
                                                                                        
                                                                                                jTable1.setModel(model2);
                                                                                                jTable1.getColumnModel().getColumn(3).setMinWidth(0);
                                                                                                jTable1.getColumnModel().getColumn(3).setMaxWidth(0);
                                                                                                jTable1.getColumnModel().getColumn(4).setMinWidth(0);
                                                                                                jTable1.getColumnModel().getColumn(4).setMaxWidth(0);
                                                                                                        jTabbedPane1.addTab("Search", jPanel2);
                                                                                                        jPanel2.setLayout(null);
                                                                                                        jPanel2.add(jLabel14);
                                                                                                        jPanel2.add(jTextField13);
                                                                                                        jPanel2.add(jButton1);
                                                                                                        jPanel2.add(jButton10);
                                                                                                        jPanel2.add(jButton11);
                                                                                                        jPanel2.add(jLabel24);
                                                                                                        jPanel2.add(jScrollPane6);

        jTabbedPane2.addTab("Fines", jPanel1);
        jPanel1.setLayout(null);
        jPanel1.add(jButton12);
        jPanel1.add(jButton13);
        jPanel1.add(jLabel15);
        jPanel1.add(jLabel30);
        jPanel1.add(jTextField14);
        jPanel1.add(jButton9);
        jPanel1.add(jCheckBox4);
        jPanel1.add(jButton5);
        jPanel1.add(jLabel31);
        jPanel1.add(jScrollPane2);

        jTabbedPane1.addTab("Others", jPanel4);
        jPanel4.setLayout(null);
        jPanel4.add(jTabbedPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jTabbedPane1, GroupLayout.PREFERRED_SIZE, 1014, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addComponent(jTabbedPane1, GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    	 resetAll();
	        setLabelText();
	        Sql_Connect sq = new Sql_Connect();
	        isbn=jTextField13.getText();
	        
	        //System.out.println(isbn +" "+ author+" "+title+" " );
	        
	        if(isbn.isEmpty()){
	            message="Enter something to search";
	        }
	        else{
	            message = sq.searchDisplay(isbn,model2);
	        }
	        jLabel24.setText(message);
	        sq.disConnect();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setLabelText();
        resetAll();
        Sql_Connect sq = new Sql_Connect();
        fname = jTextField8.getText();
        lname = jTextField15.getText();
        ssn = jTextField11.getText();
        address = jTextField16.getText();
        city =jTextField9.getText();
        state = jTextField17.getText();
        email= jTextField10.getText();
        phone = jTextField18.getText();
        if(fname.isEmpty() || lname.isEmpty()|| ssn.isEmpty() || address.isEmpty() || city.isEmpty() || state.isEmpty()){
            message = "Fields marked * are mandatory !!";
        }
        else{
            message = sq.borrowerNew(fname,lname,ssn,address,city,state,email,phone);
            if(message.equals( "Please provide the SSN in the number format XXX-XX-XXX"))
                flag=0;
            else
                flag =1;
        }
        
        jLabel22.setText(message);
        if(flag ==1){
            setTextField();
        }
        sq.disConnect();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        setLabelText();
        resetAll();
        Sql_Connect sq = new Sql_Connect();
        isbn = jTextField1.getText();
        if(jTextField3.getText().isEmpty())
        {
        	branch_id="1";
        }
        else
        { branch_id = jTextField3.getText();
        }
        	
        card_no = jTextField4.getText();
        if(isbn.isEmpty() || card_no.isEmpty())
            message = "Fields marked * are mandatory";
        else{
            message = sq.checkOut(isbn,branch_id,card_no);
            }
        jLabel23.setText(message);
        sq.disConnect();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setLabelText();
        resetAll();
        Sql_Connect sq = new Sql_Connect();
        isbn = jTextField5.getText();
        fname = jTextField6.getText();
        lname = jTextField12.getText();
        card_no = jTextField7.getText();
        if(isbn.isEmpty() && fname.isEmpty() && card_no.isEmpty() && lname.isEmpty())
            message = "Enter atleast one Field";
        else{
            message = sq.checkInDisplay(isbn,card_no,fname,lname,model1);
            setTextField();
        }
        
        jLabel12.setText(message);
        sq.disConnect();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        setLabelText();
        Sql_Connect sq = new Sql_Connect();
        int rowIndex = jTable3.getSelectedRow();
        //isbn =(String) jTable3.getValueAt(rowIndex, 0);
        
        //name = (String) jTable3.getValueAt(rowIndex, 2);
        if(rowIndex == -1)
            message = "Please Select the book row which you want to check-in";
        else{
        loan_id = (String) jTable3.getValueAt(rowIndex, 3);
        card_no = (String) jTable3.getValueAt(rowIndex, 1);
        fine_amt = (Double) jTable3.getValueAt(rowIndex, 5);
            if(fine_amt>0){
                jDialog1.setVisible(true);
                jLabel27.setText("Fine Amount: "+fine_amt);
            }
            else{
                message = sq.checkIn(loan_id);
                model1.removeRow(rowIndex);
            }
        }
        
        jLabel12.setText(message);
        sq.disConnect();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        setLabelText();
        Sql_Connect sq = new Sql_Connect();
        jDialog1.dispose();
        message = "Thank You..!! Your book has been checked in.";
        jLabel12.setText(message);
        int rowIndex = jTable3.getSelectedRow();
        loan_id = (String) jTable3.getValueAt(rowIndex, 3);
        fine_amt = (Double) jTable3.getValueAt(rowIndex, 5);
        sq.checkIn(loan_id);
        sq.fineInsert(loan_id,fine_amt,false);
        model1.removeRow(rowIndex);
        sq.disConnect();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setLabelText();
        Sql_Connect sq = new Sql_Connect();
        jTabbedPane2.setSelectedIndex(3);
        jDialog1.dispose();
        int rowIndex = jTable3.getSelectedRow();
        loan_id = (String) jTable3.getValueAt(rowIndex, 3);
        card_no = (String) jTable3.getValueAt(rowIndex, 1);
        fine_amt = (Double) jTable3.getValueAt(rowIndex, 5);
        jTextField14.setText(card_no);
        sq.checkIn(loan_id);
        sq.fineInsert(loan_id,fine_amt,false);
        sq.finesDisplay(card_no,false,model3);
        sq.disConnect();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        setLabelText();
        Sql_Connect sq = new Sql_Connect();
        int rowIndex = jTable1.getSelectedRow();
        if(rowIndex == -1){
            message = "Please Select the book row which you want to check-in";
            jLabel24.setText(message);
        }
        else{
        jTabbedPane1.setSelectedIndex(1);
        jTabbedPane2.setSelectedIndex(2);
        isbn = (String) jTable1.getValueAt(rowIndex, 0);
        resetAll();
        jTextField5.setText(isbn);
        message = sq.checkInDisplay(isbn,card_no,fname,lname,model1);
        jLabel12.setText(message);
        }
        sq.disConnect();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        setLabelText();
        Sql_Connect sq = new Sql_Connect();
        int rowIndex = jTable1.getSelectedRow();
        if(rowIndex == -1){
            message = "Please Select the book row which you want to check-out";
            jLabel24.setText(message);
        }
        else{
            jTabbedPane1.setSelectedIndex(1);
            jTabbedPane2.setSelectedIndex(1);
            isbn = (String) jTable1.getValueAt(rowIndex, 0);
            jTextField1.setText(isbn);
            branch_id = (String) jTable1.getValueAt(rowIndex, 3);
            jTextField3.setText(branch_id);
            resetAll();
        }
        sq.disConnect();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
            resetAll();
            Sql_Connect sq = new Sql_Connect();
            sq.fineUpdate();
            jLabel31.setText("Fines Updated");
            sq.disConnect();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        setLabelText();
        resetAll();
        Sql_Connect sq = new Sql_Connect();
        card_no= jTextField14.getText();
        boolean show_previous = jCheckBox4.isSelected();
        if(card_no.isEmpty())
            message="Enter Card Number";
        else{
            message= sq.finesDisplay(card_no,show_previous,model3);
        }

        jLabel31.setText(message);
        sq.disConnect();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            int rowIndex = jTable2.getSelectedRow();
            Sql_Connect sq = new Sql_Connect();
            if(rowIndex==-1)
                message = "Select a row to pay fine";
            else{
                loan_id = (String) jTable2.getValueAt(rowIndex, 0);
                paid = (String) jTable2.getValueAt(rowIndex, 3);
                book_returned = (String) jTable2.getValueAt(rowIndex, 4);
                message =sq.paidUpdate(loan_id,paid,book_returned);    
            }
            if(message.equals("Paid is updated"))
                       model3.removeRow(rowIndex);
        jLabel31.setText(message);
        sq.disConnect();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        card_no = jTextField14.getText();
        String amt;
        Sql_Connect sq = new Sql_Connect();
        if(card_no.isEmpty())
            message="Enter a Card Number";
        else{
            amt = sq.fineTotal(card_no);
            message = "Total Amount of Fine to be paid is: "+ amt;
        }
            jLabel31.setText(message);
            sq.disConnect();
    }//GEN-LAST:event_jButton13ActionPerformed
    
    private void resetAll(){
        
        for (int i = model1.getRowCount() - 1; i > -1; i--) {
                    model1.removeRow(i);
        }
        for (int i = model2.getRowCount() - 1; i > -1; i--) {
                    model2.removeRow(i);
        }
        for (int i = model3.getRowCount() - 1; i > -1; i--) {
                    model3.removeRow(i);
        }
    }
    
    private void setLabelText(){
        jLabel24.setText("");
        jLabel23.setText("");
        jLabel12.setText("");
        jLabel22.setText("");
        jLabel31.setText("");
    }
    
    private void setTextField(){
        jTextField1.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField8.setText("");
        jTextField15.setText("");
        jTextField11.setText("");
        jTextField16.setText("");
        jTextField9.setText("");
        jTextField17.setText("");
        jTextField10.setText("");
        jTextField18.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //Sql_Connect.library_connect();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
}
